annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.1.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Kubewatch is a Kubernetes watcher that currently publishes notification
  to Slack.
home: https://github.com/bitnami/charts/tree/master/bitnami/kubewatch
icon: https://bitnami.com/assets/stacks/kubewatch/img/kubewatch-stack-220x234.png
keywords:
- kubernetes
- slack
- hipchat
- mattermost
- flock
- msteams
name: kubewatch
version: 0.1.1
